server:
  port: 8604

spring:
  application:
    name: ribbonclient
  boot:
    admin:
      client:
        url: http://localhost:8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8800/eureka/