server:
  port: 8603

spring:
  application:
    name: testservice
  boot:
    admin:
      client:
        url: http://localhost:8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8800/eureka/

app:
  ip: localhost