server:
  port: 8605

spring:
  application:
    name: feignclient
  boot:
    admin:
      client:
        url: http://localhost:8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8800/eureka/
##Feign已经引入了Hystrix，所以不需要再单独引入
#修改application.yml，开启Hystrix
feign:
  hystrix:
    enabled: true