server:
  port: 8888

spring:
  application:
    name: zuul
  redis:
    host: localhost
    port: 6379
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/course?useUnicode=true&characterEncoding=UTF-8&characterSetResults=utf8&serverTimezone=GMT
    username: zhangfeng
    password: zhangfeng

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8800/eureka/
#battcn:
#  security:
#    token:
#      expiration-time: 10 # 分钟 1440
#      refresh-exp-time: 30 # 分钟 2880
#      signing-key: zhangfeng
#zuul:
#  ratelimit:
#    enabled: true
#    repository: redis
#    default-policy:
#      limit: 1
#      quota: 1
#      refresh-interval: 3
#    policies:
#      testservice:
#        limit: 10
#        quota: 50
#        refresh-interval: 60
#        type: url