server:
  port: 8602

spring:
  application:
    name: testservice
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/course?useUnicode=true&characterEncoding=UTF-8&characterSetResults=utf8&serverTimezone=GMT
    username: zhangfeng
    password: zhangfeng
  boot:
    admin:
      client:
        url: http://localhost:8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8800/eureka/

app:
  ip: localhost